import { Inter } from "next/font/google";
import { Nunito_Sans, Poppins, Manrope, DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/ui/Navbar";
import Footer from "@/ui/Footer";
import DashboardState from "@/context/DashBoard/DashboardState";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const nunito_sans_init = Nunito_Sans({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-nunito_sans",
    weight: ["400", "600", "700"],
});
export const poppins_init = Poppins({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-poppins",
    weight: ["400", "600", "700"],
});
export const manrope_init = Manrope({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-manrope",
    weight: ["400", "600", "700", "800"],
});
export const dm_sans_init = DM_Sans({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-dm-sans",
    weight: ["400", "500", "600", "700", "800"],
});

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${inter.className} ${nunito_sans_init.variable} ${poppins_init.variable} ${manrope_init.variable} ${dm_sans_init.variable}`}
            >
                {/* <Navbar /> */}
                <DashboardState>
                {children}
                {/* <Footer /> */}
                </DashboardState>
            </body>
        </html>
    );
}
